//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EntityCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int Step { get; set; }
        public int IdTxTypeFK { get; set; }
        public string NameOrig { get; set; }
        public decimal OldbalanceOrg { get; set; }
        public decimal Amount { get; set; }
        public decimal NewbalanceOrig { get; set; }
        public string NameDest { get; set; }
        public decimal OldBalanceDest { get; set; }
        public decimal NewBalanceDest { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public bool IsFraud { get; set; }
    
        public virtual TransactionType TransactionType { get; set; }
    }
}
